### ISSUE TITLE
Crashes on Win11 23H2

### ISSUE THREAD

**Issue by jeffmcjunkin** [blurbdust/gpugen-dist#1]
```
client.winx64.exe
Folder already exists, skipping download
File 'netntlmv1_byte#7-7_0_2x1_0.rt' deleted
Started process in directory C:\Users\jeff\Downloads\crackalack\rainbowcrackalack-win-x64
panic: exit status 0xffffffff

goroutine 1 [running]:
main.helpCheck({0xc000010340?, 0x3c?}, {0xa39645, 0x14}, {0xa3dff0, 0x1d}, {0xc000010340, 0x3c}, 0xffffffffffffffff)
        C:/Users/user/GolandProjects/gpugen-dist/client.go:178 +0x4ae
main.runCheck({0xa411ee, 0x24}, {0xa39645, 0x14})
        C:/Users/user/GolandProjects/gpugen-dist/client.go:203 +0x13b
main.main()
        C:/Users/user/GolandProjects/gpugen-dist/client.go:418 +0x46
```

**Comment by jeffmcjunkin** [comment]
Same problem when compiling from the repo:
```
C:\Users\jeff\gpugen-dist>go build client.go
C:\Users\jeff\gpugen-dist>client.exe
Archive downloaded and extracted successfully!
File 'netntlmv1_byte#7-7_0_2x1_0.rt' does not exist
Started process in directory C:\Users\jeff\gpugen-dist\crackalack\rainbowcrackalack-win-x64
panic: exit status 0xffffffff

goroutine 1 [running]:
main.helpCheck({0xc00091c000?, 0x3e?}, {0x7eda3b, 0x14}, {0x7f2417, 0x1d}, {0xc00091c000, 0x3e}, 0xffffffffffffffff)
        C:/Users/jeff/gpugen-dist/client.go:178 +0x4a6
main.runCheck({0x7f5a9e, 0x24}, {0x7eda3b, 0x14})
        C:/Users/jeff/gpugen-dist/client.go:203 +0x139
main.main()
        C:/Users/jeff/gpugen-dist/client.go:418 +0xb7

C:\Users\jeff\gpugen-dist>go run client.go
Folder already exists, skipping download
File 'netntlmv1_byte#7-7_0_2x1_0.rt' deleted
Started process in directory C:\Users\jeff\gpugen-dist\crackalack\rainbowcrackalack-win-x64
panic: exit status 0xffffffff

goroutine 1 [running]:
main.helpCheck({0xc000010780?, 0x3e?}, {0x102da3b, 0x14}, {0x1032417, 0x1d}, {0xc000010780, 0x3e}, 0xffffffffffffffff)
        C:/Users/jeff/gpugen-dist/client.go:178 +0x4a6
main.runCheck({0x1035a9e, 0x24}, {0x102da3b, 0x14})
        C:/Users/jeff/gpugen-dist/client.go:203 +0x139
main.main()
        C:/Users/jeff/gpugen-dist/client.go:418 +0xb7
exit status 2
```
